set_property SRC_FILE_INFO {cfile:D:/240/hw2b/hw2b.srcs/constrs_1/new/constraints.xdc rfile:../../../hw2b.srcs/constrs_1/new/constraints.xdc id:1} [current_design]
set_property src_info {type:XDC file:1 line:1 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN P16 [get_ports {GPIO_0_0_tri_io[0]}]
set_property src_info {type:XDC file:1 line:3 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN K18 [get_ports {GPIO_0_tri_io[0]}]
